### ISSUE TITLE
Serverless plugin "serverless-appsync-plugin" initialization errored: Cannot find module 'aws-sdk'

### ISSUE THREAD

**Issue by fans3210** [sid88in/serverless-appsync-plugin#165]
After upgrade to 1.0.5, got this error when I would like to deploy
Serverless plugin "serverless-appsync-plugin" initialization errored: Cannot find module 'aws-sdk'

 
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-appsync-plugin" initialization errored: Cannot find module 'aws-sdk'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.32.0

**Comment by fans3210** [comment]
no issue with 1.0.4

**Comment by fans3210** [comment]
@kinyat thanks a lot!

**Comment by SET001** [comment]
this should be either internal dependency of this plugin or somewhere have to a mention that it should be installed
